### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by johnnygoodface** [guymcswain/pigpio-client#25]
after the sudo make install, I get:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
make: *** [Makefile:107: install] Error 1

**Comment by guymcswain** [comment]
Per the [pigpio documentation:](http://abyz.me.uk/rpi/pigpio/download.html)

> If the Python part of the install fails it may be because you need the setup tools.
sudo apt install python-setuptools python3-setuptools
