### ISSUE TITLE
Latest Installation Unit File In Git Is Wrong

### ISSUE THREAD

**Issue by dachshund-digital** [guymcswain/pigpio-client#26]
Disregard... I posted issue to the wrong solution... the issue is with the pigpiod solution, not this client.  I must have miss-clicked something.

**Comment by guymcswain** [comment]
Can you be more specific, I'm not following.

**Comment by dachshund-digital** [comment]
Oh, sure.  If you do the typical install as per your write up pulling from git, the unit file that results points to /sbin/pigpiod.  But the actual location of the daemon is at /usr/local/pigpiod.  The example unit file you have in the your write is correct but the one deploy is incorrect.

**Comment by guymcswain** [comment]
> Disregard... I posted issue to the wrong solution... the issue is with the pigpiod solution, not this client
