### ISSUE TITLE
Notify on only one edge

### ISSUE THREAD

**Issue by jmbldwn** [guymcswain/pigpio-client#32]
I might just be missing it, but I can't figure out how to set up a notify for only falling or rising edges.

Is this implemented?

**Comment by guymcswain** [comment]
The notifier is implemented for either edge.  Use the level argument to filter for the edge you want.  It was a decision that I made, quite a while ago, to keep things simple.

**Comment by jmbldwn** [comment]
Thanks.  While it does mean twice as much traffic over the socket, I don't think it's a big deal.

**Comment by jmbldwn** [comment]
Does the pigpiod socket protocol support configuring alerts for one edge?  It's hard to tell from the docs.  If it doesn't it would require changes to the daemon as well, which would be a lot of work.

**Comment by jmbldwn** [comment]
Looks like the `pigs` protocol can only turn notifications on and off, no filtering on edges, so without a feature update to the daemon this isn't possible.

**Comment by guymcswain** [comment]
You may be right.  The python client filters but it made do so only after having received both edges (traffic).

**Comment by jmbldwn** [comment]
So this is an optimization.  The pigpio repo has a long list of issues, but might be worth adding this as a feature request.

**Comment by jmbldwn** [comment]
OK, I logged an issue on pigpio for this.  No point in worrying about it here on the client until we get daemon support.

**Comment by guymcswain** [comment]
Ok, well that will come back to me since I'm currently the maintainer of pigpio.

**Comment by jmbldwn** [comment]
:-)  You're a star.  Let me know if/how I can help.
